### ISSUE TITLE
Add contents to first half of course

### ISSUE THREAD

**Issue by larryjl** [zero-to-mastery/complete-web-developer-manual#11]
I am thinking of listing the names of methods and concepts covered in some of the sections up to 13. Would that be in scope of this document?

**Comment by aneagoie** [comment]
I think that is a great idea. Go ahead with it and do a Pull Request when you are ready :)

**Comment by sophiabrandt** [comment]
@larryjl are you still interested in this?
Otherwise I will close the issue, if nobody else wants to tackle it.

**Comment by larryjl** [comment]
No I've done some but won't be going further thanks.

**Comment by sophiabrandt** [comment]
I will be closing the issue for now. If someone else wants to add more content, they can open a new issue or pull request.
Thank you for the quick answer, @larryjl .
