### ISSUE TITLE
Invalid Discord invite

### ISSUE THREAD

**Issue by YeapGuy** [zero-to-mastery/complete-web-developer-manual#15]
Hey! The Discord guild invite has probably expired, both the one in the course and the link here are invalid! Could you please update the links? Thank you!

**Comment by aneagoie** [comment]
The invite is still active, but only for students who enrolled in the course through zerotomastery.io or udemy :)

**Comment by YeapGuy** [comment]
Oh! The one in the course is actually valid, I'm in now, thank you!

**Comment by djembaasd** [comment]
Can someone send the invitation code plase? :)

**Comment by aneagoie** [comment]
The invitation is only available for valid students signed up for one of the courses on zerotomastery.io or Udemy. You can find the link there.

**Comment by Fuglydami** [comment]
I purchased your course via udemy an i can't find the discord download  link

**Comment by MattCSmith** [comment]
@Fuglydami You can download the discord app from their website discord.com

You can find the invite link in the first section of any Zero to Mastery course. Failing that message Andrei through Udemy.

**Comment by baboucarrgibba** [comment]
> The invite is still active, but only for students who enrolled in the course through zerotomastery.io or udemy :)
 sir i bought the course in udemy but am not in discord community, how can I join , my discord sparker#8681

**Comment by ishakalpa** [comment]
> The invite is still active, but only for students who enrolled in the course through zerotomastery.io or udemy :)

sir i have joined with udemy data structures course nove 26 2022 . then i joined with discode and again i tried to log in to discode at 28th november today . i cannot log in it says invalid invitation link . please help

**Comment by ekoue** [comment]
> The invitation is only available for valid students signed up for one of the courses on zerotomastery.io or Udemy. You can find the link there.

Hello @aneagoie how can I get access to the classroom the link in udemy js course lecture3 in not valid anymore. Thanks
