### ISSUE TITLE
Missprint?

### ISSUE THREAD

**Issue by BizFounder** [zero-to-mastery/complete-web-developer-manual#23]
19. React.js + Redux
npm install –g create-react-app
create-react-app “name” 
**[cd "name"]**
npm start
npm install tachyons

**Comment by sophiabrandt** [comment]
Good catch.
Why don't you make a pull request with updated guidelines?
For example, we could copy from https://create-react-app.dev/docs/getting-started#quick-start
```bash
npx create-react-app my-app
cd my-app
npm start
```
