### ISSUE TITLE
ADD IN ORGANISATION

### ISSUE THREAD

**Issue by ARYAN-CODES-STAR** [zero-to-mastery/complete-web-developer-manual#83]
Add me to the ZTM organisation, I believe I will bring quality to the community.

**Comment by mohdahsanrazakhan** [comment]
You should contribute your first PR in ZTM. After first PR you'll receive invitation to join ZTM GitHub Organization below your open PR., then you'll follow the guide to become a member of ZTM Organization.
All the best for your first contribution in the Zero To Mastery Organization!
